### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by LinearDynamics** [MrCrayfish/Controllable#120]
Finally was able to have my 3 year old play MC with us for the first time! We played a bunch last night and he loved playing with the controller.
This morning, the game is crashing on launch.
Please help a 3 year old play MC and keep a dad sane!

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 10/29/20 8:20 AM
Description: Initializing game

java.lang.IllegalStateException: GLFW error before init: [0x10004]Invalid button in gamepad mapping 030000000d0f0000ee00000000000000 (HORIPAD mini4)
at com.mojang.blaze3d.platform.GLX.func_229879_lam_(SourceFile:64) ~[?:?] {re:classloading}
at com.mojang.blaze3d.platform.GLX$$Lambda$2824/1818453711.accept(Unknown Source) ~[?:?] {}
at net.minecraft.client.MainWindow.func_211162_a(MainWindow.java:131) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:63) ~[?:?] {re:classloading}
at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:1038) ~[?:?] {re:classloading}
at net.minecraft.client.Minecraft.(Minecraft.java:403) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:controllable:send_click,xf:fml:controllable:process_keys,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.33.jar:34.1] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$426/1367594377.call(Unknown Source) [forge-1.16.3-34.1.33.jar:34.1] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.5.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.5.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.5.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-8.0.5.jar:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-8.0.5.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Render thread
Stacktrace:
at com.mojang.blaze3d.platform.GLX.func_229879_lam_(SourceFile:64) ~[?:?] {re:classloading}
at com.mojang.blaze3d.platform.GLX$$Lambda$2824/1818453711.accept(Unknown Source) ~[?:?] {}
at net.minecraft.client.MainWindow.func_211162_a(MainWindow.java:131) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:63) ~[?:?] {re:classloading}
at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:1038) ~[?:?] {re:classloading}
at net.minecraft.client.Minecraft.(Minecraft.java:403) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:controllable:send_click,xf:fml:controllable:process_keys,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.33.jar:34.1] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$426/1367594377.call(Unknown Source) [forge-1.16.3-34.1.33.jar:34.1] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.5.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.5.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.5.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-8.0.5.jar:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-8.0.5.jar:?] {}

-- System Details --
Details:
Minecraft Version: 1.16.3
Minecraft Version ID: 1.16.3
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 818556992 bytes (780 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
CPUs: 8
JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
Launched Version: 1.16.3-forge-34.1.33
Backend library: LWJGL version 3.2.2 build 10
Backend API: NO CONTEXT
GL Caps:
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'forge'
Type: Client (map_client.txt)
CPU:
```

**Comment by LinearDynamics** [comment]
To anyone rolling in here from a google search: I removed the controllable plugin. Still got this error(so added back the plugin to /mods/). 
Workaround: Run MC launcher, start game with the Forge profile, on title screen: plug in the controller, load world. Works!

**Comment by MrCrayfish** [comment]
Is this still a problem on the latest version of the mod?

**Comment by LinearDynamics** [comment]
Last time I spent 20 minutes at it was two weeks ago. Same crash issue.
I can supply more logs, etc tomorrow.
________________________________

**Comment by MrCrayfish** [comment]
Does this happen with a different controller? I suggest possibly trying [DS4Windows](https://github.com/Ryochan7/DS4Windows/releases), it's a software that wraps input and make windows think it's an xbox controller.

**Comment by MrCrayfish** [comment]
I recommend updating to modern version of Controllable due to this being reported on an outdated version, may changes have happened since. If you have any other issues, I've written a full documentation for Controllable which can help with different methods of connecting controllers and troubleshooting issues: https://mrcrayfish.gitbook.io/controllable-documentation/
