### ISSUE TITLE
Cannot mine or select anything in the inventory.

### ISSUE THREAD

**Issue by oskarparsim** [MrCrayfish/Controllable#161]
Using 1.16.5. Cannot mine because holding the button only does one punch. Cannot select anything in inventory because as soon as i click on it, the cursor will start following the mouse.

**Comment by MrCrayfish** [comment]
Are you using the latest version?

**Comment by nitrozeus2700** [comment]
I had to install version 0.11.2, which is the last version of the mod and the mod is not displayed when I run the game. I have installed forge for 1.16.5 with the 0.11.0 version of the mod and that worked great but when i go into survival i can't break the blocks i can just give a punch so i looked in the comments and saw someone who had the same problem i saw you wrote to him that if he had install the latest version then I change it to version 0.11.2 of the mod and it does not show up in the mode bar. what do I do?

**Comment by kcattle** [comment]
I also have this issue of only hitting one or two blocks. I am using the latest version of everything.

**Comment by nitrozeus2700** [comment]
hi kcattle, i have recently fixed the problem, if you are playing on forge version 1.16.5 i guess you just need to download the mod in the file tab and you have to download the 0.11.0 version of the mod on the version 1.16.5 of minecraft I send you a photo so that you know which one to install

**Comment by nitrozeus2700** [comment]
![20210412_183617](https://user-images.githubusercontent.com/82093298/114471140-1c8c9980-9bbe-11eb-831e-668ba270b8d4.png)

**Comment by MrCrayfish** [comment]
If using 1.15, you need to be running at least Forge 31.2.45 as Mixins don't exist in lower versions. The latest version for 1.16 is `0.11.0`, `0.11.2` is for 1.15

**Comment by kcattle** [comment]
> hi kcattle, i have recently fixed the problem, if you are playing on forge version 1.16.5 i guess you just need to download the mod in the file tab and you have to download the 0.11.0 version of the mod on the version 1.16.5 of minecraft I send you a photo so that you know which one to install


I was unable to get this to work, it crashes everytime I use it. I am using 1.16.5 Minecraft Version, and 1.16.5-36.1.0 Forge, and then the 0.11.0 Controllable uploaded on February 9th. Am I doing something else wrong? I was able to get a the version 0.8.4_1.16.43 of Controllable to work for the most part except the inventory menu issue. Sorry for not understanding. Definitely a newb.

**Comment by MrCrayfish** [comment]
Can you send the crash log?

**Comment by kcattle** [comment]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 4/13/21 6:07 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:controllable.mixins.json:client.OptifineGameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.systems.RenderSystem.assertThread(SourceFile:85) ~[?:?] {re:mixin,re:classloading}
-- MOD controllable --
Details:
	Mod File: controllable-0.11.0-1.16.3.jar
	Failure message: Controllable (controllable) encountered an error during the sided_setup event phase
		java.lang.IllegalStateException: Rendersystem called from wrong thread
	Mod Version: 0.11.0
	Mod Issue URL: https://github.com/MrCrayfish/Controllable/issues
	Exception message: java.lang.IllegalStateException: Rendersystem called from wrong thread
Stacktrace:
	at com.mojang.blaze3d.systems.RenderSystem.assertThread(SourceFile:85) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.MainWindow.func_198084_a(MainWindow.java:285) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36) ~[lwjgl-glfw-3.2.1.jar:build 12] {}
	at org.lwjgl.system.JNI.invokePI(Native Method) ~[lwjgl-3.2.1.jar:build 12] {}
	at org.lwjgl.glfw.GLFW.nglfwUpdateGamepadMappings(GLFW.java:4170) ~[lwjgl-glfw-3.2.1.jar:build 12] {}
	at org.lwjgl.glfw.GLFW.glfwUpdateGamepadMappings(GLFW.java:4198) ~[lwjgl-glfw-3.2.1.jar:build 12] {}
	at com.mrcrayfish.controllable.Controllable.onClientSetup(Controllable.java:87) ~[?:0.11.0-1.16.3] {re:mixin,re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.15.7
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 794530080 bytes (757 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |ENQUEUE_IM|NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |ENQUEUE_IM|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		controllable-0.11.0-1.16.3.jar                    |Controllable                  |controllable                  |0.11.0              |ERROR     |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
	Crash Report UUID: 2f2ef566-71cc-4e8f-bd43-f0c16ff5404a
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-14.7.12
	OpenGlRenderer: Intel(R) HD Graphics 6000
	OpenGlVendor: Intel Inc.
	CpuCount: 4
