### ISSUE TITLE
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Controllable (controllable)

### ISSUE THREAD

**Issue by yanonbusiness** [MrCrayfish/Controllable#206]
The mod was working in 1.12.2 just fine, until it wasn't. This message keeps showing up even with no other mods installed.
Crash report: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Controllable (controllable-1.12.2-0.3.1.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CoreModLoader (Sound-Physics-1.12.2-1.0.10-1.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 5/28/21 8:40 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Controllable (controllable)
Caused by: java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at com.mrcrayfish.controllable.client.Mappings.loadMapping(Mappings.java:138)
	at com.mrcrayfish.controllable.client.Mappings.loadMapping(Mappings.java:127)
	at com.mrcrayfish.controllable.client.Mappings.load(Mappings.java:46)
	at com.mrcrayfish.controllable.Controllable.onPreInit(Controllable.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5477218808 bytes (5223 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -Xmx6G -Xms6G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                  | Source                                 | Signature                                |
	|:----- |:------------------- |:------------------------ |:-------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2                   | minecraft.jar                          | None                                     |
	| LCH   | mcp                 | 9.42                     | minecraft.jar                          | None                                     |
	| LCH   | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | ivtoolkit           | 1.3.3-1.12               | minecraft.jar                          | None                                     |
	| LCE   | controllable        | 0.3.1                    | controllable-1.12.2-0.3.1.jar          | None                                     |
	| LC    | bettercaves         | 1.12.2                   | bettercaves-1.12.2-2.0.2.jar           | None                                     |
	| LC    | camoucreepers       | 1.6                      | camoucreepers-1.6.jar                  | None                                     |
	| LC    | craftstudioapi      | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar  | None                                     |
	| LC    | orelib              | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar              | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | dsurround           | 3.6.1.0                  | DynamicSurroundings-1.12.2-3.6.1.0.jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | extrautils2         | 1.0                      | extrautils2-1.12-1.9.9.jar             | None                                     |
	| LC    | gravestone          | 1.10.2                   | gravestone-1.10.2.jar                  | None                                     |
	| LC    | hardcoredarkness    | 2.0                      | HardcoreDarkness-MC1.12.2-2.0.jar      | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LC    | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar               | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | jei                 | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar              | None                                     |
	| LC    | lostcities          | 2.0.22                   | lostcities-1.12-2.0.22.jar             | None                                     |
	| LC    | mobends             | 0.24                     | mobends-0.24_for_MC-1.12.jar           | None                                     |
	| LC    | openglider          | @VERSION@                | OpenGlider-1.12.1-1.1.0.jar            | None                                     |
	| LC    | reccomplex          | 1.4.8.1                  | RecurrentComplex-1.4.8.1.jar           | None                                     |
	| LC    | soundphysics        | 1.0.10-1                 | Sound-Physics-1.12.2-1.0.10-1.jar      | None                                     |
	| LC    | tektopia            | 1.0.93                   | tektopia-1.0.93.jar                    | None                                     |
	| LC    | veinminer           | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar  | None                                     |
	| LC    | veinminermodsupport | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar  | None                                     |

	Loaded coremods (and transformers): 
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
Controllable (controllable-1.12.2-0.3.1.jar)
  com.mrcrayfish.controllable.asm.ControllableTransformer
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CoreModLoader (Sound-Physics-1.12.2-1.0.10-1.jar)
  com.sonicether.soundphysics.CoreModInjector
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 466.47' Renderer: 'NVIDIA GeForce RTX 2070/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.29 Extreme.zip
	OpenGlVersion: 4.6.0 NVIDIA 466.47
	OpenGlRenderer: NVIDIA GeForce RTX 2070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by KorewaLidesu** [comment]
Delete Controllable config
