### ISSUE TITLE
Crash need help

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/Controllable#292]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Controllable (controllable-0.11.2-mc1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 4/30/22 11:21 AM
Description: Unexpected error

java.lang.NoSuchMethodError: com.mrcrayfish.controllable.client.Controller.getState()Lcom/studiohartman/jamepad/ControllerState;
	at com.mrcrayfish.guns.client.ControllerEvents.onRender(ControllerEvents.java:174)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_115_ControllerEvents_onRender_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:355)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.guns.client.ControllerEvents.onRender(ControllerEvents.java:174)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_115_ControllerEvents_onRender_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheCreeperGuy'/917, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['TheCreeperGuy'/917, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 871108976 bytes (830 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID           | Version      | Source                           | Signature                                |
	|:------ |:------------ |:------------ |:-------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft    | 1.12.2       | minecraft.jar                    | None                                     |
	| LCHIJA | mcp          | 9.42         | minecraft.jar                    | None                                     |
	| LCHIJA | FML          | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge        | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | controllable | 0.11.2       | controllable-0.11.2-mc1.12.2.jar | None                                     |
	| LCHIJA | obfuscate    | 0.4.2        | minecraft.jar                    | None                                     |
	| LCHIJA | cdm          | 0.4.1        | cdm-0.4.1-mc1.12.2.jar           | None                                     |
	| LCHIJA | cfm          | 6.3.0        | cfm-6.3.0-mc1.12.2.jar           | None                                     |
	| LCHIJA | cgm          | 0.15.3       | cgm-0.15.3-mc1.12.2.jar          | None                                     |
	| LCHIJA | jei          | 4.16.1.301   | jei_1.12.2-4.16.1.301.jar        | None                                     |
	| LCHIJA | vehicle      | 0.44.1       | vehicle-0.44.1-mc1.12.2.jar      | None                                     |
	| LCHIJA | reauth       | 3.6.0        | reauth-3.6.0.jar                 | daba0ec4df71b6da841768c49fb873def208a1e3 |

	Loaded coremods (and transformers): 
Controllable (controllable-0.11.2-mc1.12.2.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.9365' Renderer: 'Intel(R) Iris(R) Plus Graphics'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: Intel(R) Iris(R) Plus Graphics GL version 4.6.0 - Build 27.20.100.9365, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.9365
	OpenGlRenderer: Intel(R) Iris(R) Plus Graphics
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by ghost** [comment]
removed ofuscate needed mods

**Comment by MrCrayfish** [comment]
Downgrade Controllable to an older version. The latest version on 1.12.2 is not compatible with the latest version of the Gun Mod on 1.12.2. This is the only solution as I no longer maintain the 1.12.2 version of either mods.
