### ISSUE TITLE
 Controllable (controllable-0.11.2-1.12.2.jar)

### ISSUE THREAD

**Issue by LordVardus** [MrCrayfish/Controllable#350]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Controllable (controllable-0.11.2-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 11/11/22 10:36 AM
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.remove(HashMap.java:1443)
	at net.minecraft.client.renderer.RenderGlobal.func_72734_e(RenderGlobal.java:1786)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1835)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by MrCrayfish** [comment]
I no longer maintain the 1.12.2 version of the mod.
