### ISSUE TITLE
PojavLauncher with forge + controllable 1.19.3

### ISSUE THREAD

**Issue by khalimwu** [MrCrayfish/Controllable#374]
Install forge for 1.19.3 (using pojavlauncher default settings)
Copy controllable mod to mods folder
Launch

Result:
Game crashes after loading screen (forge do not crash if we don't use controllable mod)

Log:
attached
[latest.log](https://github.com/MrCrayfish/Controllable/files/10774475/latest.log)

Caused by: java.lang.NullPointerException: Cannot invoke "com.mrcrayfish.controllable.client.ControllerInput.getLastUse()" because "input" is null
	at net.minecraft.client.renderer.GameRenderer.modify$zzd000$modifyMouseX(GameRenderer.java:1550) ~[client-1.19.3-20221207.122022-srg.jar%23124!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:931) ~[client-1.19.3-20221207.122022-srg.jar%23124!/:?]

**Comment by MrCrayfish** [comment]
I don't fix any issues related to PojavLuancher
