### ISSUE TITLE
1.20 not working

### ISSUE THREAD

**Issue by Beeple1** [MrCrayfish/Controllable#426]
Made a new instance on steamdeck to play modded 1.20 and controllable isn’t working. Using 1.20.1 every mod works including framework but as soon as any variation of controllable is added I get error 255

**Comment by MegPredator** [comment]
got optifine installed?

**Comment by Beeple1** [comment]
> 

Hey no I don’t have optifine can’t get it to work on my deck is it required?

**Comment by MegPredator** [comment]
No, I asked because as of right now optifine causes issues with controllable. Can you send latest.log ?

**Comment by Beeple1** [comment]
Hey sorry I have to ask how do I get the log for the error from my steamdeck? I’ve never done it before

**Comment by MegPredator** [comment]
you are probably using the flatpak, well go to your home directory, enable hidden folders, then go to /.var/app/org.polymc.PolyMC/data/PolyMC/instances/Modded Survival/.minecraft/logs/latest.log

PolyMC is one of the available flatpak launchers, others exist and they will have different package names

**Comment by DonkeyDave** [comment]
I'm on Steam Deck and having the same problem on the same version. here is what's in my latest.log:

[02:10:16] [main/INFO]: ModLauncher running: args [--username, Name1is2my3Name, --version, 1.20.1, --gameDir, /home/deck/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/instances/control test, --assetsDir, /home/deck/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets, --assetIndex, 5, --uuid, f48107f09dbe49f98e8c31cd74853a08, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, --xuid, --userType, mojang, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.1, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, --width=854, --height=480]
[02:10:16] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 21 by Oracle Corporation; OS Linux arch amd64 version 5.13.0-valve37-1-neptune
[02:10:16] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[02:10:16] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/deck/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2388!/ Service=ModLauncher Env=CLIENT
[02:10:19] [main/INFO]: Compatibility level set to JAVA_17
[02:10:19] [main/INFO]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, /home/deck/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/instances/control test, --assetsDir, /home/deck/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/assets, --uuid, f48107f09dbe49f98e8c31cd74853a08, --username, Name1is2my3Name, --assetIndex, 5, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, --xuid, --userType, mojang, --versionType, release, --width=854, --height=480]
[02:10:19] [main/WARN]: Error loading class: mezz/jei/gui/elements/GuiIconToggleButton (java.lang.ClassNotFoundException: mezz.jei.gui.elements.GuiIconToggleButton)
[02:10:19] [main/WARN]: Error loading class: mezz/jei/gui/overlay/IngredientGrid (java.lang.ClassNotFoundException: mezz.jei.gui.overlay.IngredientGrid)
[02:10:19] [main/WARN]: Error loading class: mezz/jei/gui/overlay/IngredientGridWithNavigation (java.lang.ClassNotFoundException: mezz.jei.gui.overlay.IngredientGridWithNavigation)
[02:10:19] [main/WARN]: Error loading class: mezz/jei/gui/overlay/IngredientListOverlay (java.lang.ClassNotFoundException: mezz.jei.gui.overlay.IngredientListOverlay)
[02:10:19] [main/WARN]: Error loading class: mezz/jei/gui/input/MouseUtil (java.lang.ClassNotFoundException: mezz.jei.gui.input.MouseUtil)
[02:10:19] [main/WARN]: Error loading class: mezz/jei/gui/PageNavigation (java.lang.ClassNotFoundException: mezz.jei.gui.PageNavigation)
[02:10:31] [modloading-worker-0/INFO]: Forge mod loading, version 47.2.1, for MC 1.20.1 with MCP 20230612.114412
[02:10:31] [modloading-worker-0/INFO]: MinecraftForge v47.2.1 Initialized
[02:10:33] [Forge Version Check/INFO]: [framework] Starting version check at https://mrcrayfish.com/modupdatejson?id=framework
[02:10:34] [Forge Version Check/INFO]: [framework] Found status: BETA Current: 0.6.16 Target: 0.6.16
[02:10:34] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[02:10:35] [Forge Version Check/INFO]: [forge] Found status: AHEAD Current: 47.2.1 Target: null
[02:10:35] [Forge Version Check/INFO]: [controllable] Starting version check at https://mrcrayfish.com/modupdatejson?id=controllable
[02:10:35] [Forge Version Check/INFO]: [controllable] Found status: BETA Current: 0.20.3 Target: 0.20.3
[02:10:39] [Render thread/ERROR]: Exception caught during firing event: Error looking up function 'SDL_GetJoystickGUIDInfo': /usr/lib/x86_64-linux-gnu/libSDL2.so: undefined symbol: SDL_GetJoystickGUIDInfo
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: com.mrcrayfish.framework.client.ClientForgeEvents@28295554 onRenderTick(Lnet/minecraftforge/event/TickEvent$RenderTickEvent;)V
java.lang.UnsatisfiedLinkError: Error looking up function 'SDL_GetJoystickGUIDInfo': /usr/lib/x86_64-linux-gnu/libSDL2.so: undefined symbol: SDL_GetJoystickGUIDInfo
	at MC-BOOTSTRAP/com.sun.jna@5.12.1/com.sun.jna.Function.<init>(Function.java:252)
	at MC-BOOTSTRAP/com.sun.jna@5.12.1/com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:604)
	at MC-BOOTSTRAP/com.sun.jna@5.12.1/com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:580)
	at MC-BOOTSTRAP/com.sun.jna@5.12.1/com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566)
	at MC-BOOTSTRAP/com.sun.jna@5.12.1/com.sun.jna.Native.register(Native.java:1904)
	at TRANSFORMER/libsdl4j@2.26.4-1.2/io.github.libsdl4j.jna.SdlNativeLibraryLoader.registerNativeMethods(SdlNativeLibraryLoader.java:26)
	at TRANSFORMER/libsdl4j@2.26.4-1.2/io.github.libsdl4j.api.joystick.SdlJoystick.<clinit>(SdlJoystick.java:41)
	at TRANSFORMER/controllable@0.20.3/com.mrcrayfish.controllable.client.input.sdl2.SDL2ControllerManager.getRawControllerCount(SDL2ControllerManager.java:53)
	at TRANSFORMER/controllable@0.20.3/com.mrcrayfish.controllable.client.input.ControllerManager.tick(ControllerManager.java:54)
	at TRANSFORMER/controllable@0.20.3/com.mrcrayfish.controllable.client.InputProcessor.gatherAndQueueControllerInput(InputProcessor.java:63)
	at TRANSFORMER/controllable@0.20.3/com.mrcrayfish.controllable.client.InputProcessor.pollControllerInput(InputProcessor.java:51)
	at TRANSFORMER/controllable@0.20.3/com.mrcrayfish.controllable.client.InputProcessor.lambda$new$0(InputProcessor.java:43)
	at TRANSFORMER/framework@0.6.16/com.mrcrayfish.framework.api.event.TickEvents.lambda$static$19(TickEvents.java:39)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at TRANSFORMER/framework@0.6.16/com.mrcrayfish.framework.api.event.TickEvents.lambda$static$20(TickEvents.java:39)
	at TRANSFORMER/framework@0.6.16/com.mrcrayfish.framework.client.ClientForgeEvents.onRenderTick(ClientForgeEvents.java:86)
	at TRANSFORMER/framework@0.6.16/com.mrcrayfish.framework.client.__ClientForgeEvents_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.1/net.minecraftforge.event.ForgeEventFactory.onRenderTickStart(ForgeEventFactory.java:905)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1144)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91362_(Minecraft.java:2141)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91320_(Minecraft.java:2110)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91394_(Minecraft.java:1312)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:736)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.1/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.1/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.1/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

[02:10:39] [Render thread/FATAL]: Preparing crash report with UUID bdf8dd58-1890-44db-bcf8-178da7a40614
[02:10:39] [Render thread/FATAL]: Preparing crash report with UUID 028c8678-3791-49e0-8e15-a53c9736c236

**Comment by reck179** [comment]
I am having the same issue here on v1.20.6 . I was trying to get the new 1.21 to work but ended up resorting to 1.20, still without success.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/39bb8d72f5f5cb3c94466aee663d43e681b27ae7
