### ISSUE TITLE
Telling me to install framework

### ISSUE THREAD

**Issue by ChaoticUltimateJ** [MrCrayfish/Controllable#435]
Minecraft version 1.19.4

Mod installed from [forge](https://www.curseforge.com/minecraft/mc-mods/controllable-fabric/files?version=1.19.4)
Latest release of fabric API installed (0.86.1+1.19.4 as I'm writing this)

I do not know what will fix this error I just wanted to play Minecraft with a controller 😭 

If there is something else I need to install please tell me.

Error
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install framework, version 0.6.4 or later.
Unmet dependency listing:
	 - Mod 'Controllable' (controllable) 0.19.2 requires version 0.6.4 or later of framework, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ChaoticUltimateJ** [comment]
Nvm. They should've made the dependency warning bigger.
