### ISSUE TITLE
1.16.5 crash

### ISSUE THREAD

**Issue by JiuyeAyan** [MrCrayfish/Controllable#436]
I sent the crash report to AI, and AI told me:

_The issue lies in the two Mixin configurations - controllable.mixins.json and com.teammoeg.frostedheart.mixin.client.IngameGuiMixin. They both try to inject into the same method in net.minecraft.client.gui.IngameGui, causing an injection conflict.
It's recommended to check these two Mixin configs and see if you can remove or modify one of them to avoid injecting into the same method. You can also adjust the injection priority to avoid the conflict.
If it's unresolvable, you may need to contact the corresponding Mod developers for help and see if the issue caused by the Mixin injection can be fixed from the root.
In summary, injection conflicts are common issues with Mixins. Carefully examining the conflicting Mixins and making proper adjustments may help resolve it._

I know controllable.mixins.json should be Controllable this mod, but I don't know what com.teammoeg.frostedheart.mixin.client.IngameGuiMixin is.
Can u help me to modify the injection priority? or and thing would help me launch my game?

I'm playing The Winter Rescure pack:
https://www.curseforge.com/minecraft/modpacks/the-winter-rescue

here are my mods list: 
ages-api-1.16.5-1.2.0.jar
architectury-1.32.66.jar
BetterAdvancements-1.16.5-0.1.1.115.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar
BetterStrongholds-1.16.4-1.2.1.jar
Bookshelf-Forge-1.16.5-10.4.31.jar
cfm-7.0.0pre22-1.16.3.jar
charcoal_pit-1.16.5-2.42.jar
Chisel-MC1.16.5-2.0.1-alpha.4.jar
ClientTweaks_1.16.3-5.3.0.jar
cloth-config-4.12.41-forge.jar
comforts-forge-1.16.5-4.0.1.3.jar
configured-1.5.3-1.16.5.jar
corpse-1.16.5-1.0.6.jar
create-mc1.16.5_v0.3.2g.jar
CrockPot-1.16.5-2.1.0-release.jar
CTM-MC1.16.1-1.1.2.6.jar
Cucumber-1.16.5-4.1.12.jar
curios-forge-1.16.5-4.0.5.3.jar
CustomSkinLoader_ForgeLegacy-14.13-SNAPSHOT-303.jar
diet-forge-1.16.5-1.0.4.0.jar
drippyloadingscreen_1.3.1_MC_1.16.2-1.16.5.jar
elevatorid-1.16.5-1.7.13.jar
EnchantmentDescriptions-1.16.5-7.0.12.jar
engineersdecor-1.16.5-1.1.15.jar
fancymenu_2.4.0_MC_1.16.2-1.16.5.jar
ferritecore-2.1.0-forge.jar
flywheel-1.16-0.2.5.jar
frostedheart-1.16.5-0.5.5-stable1-hf1.jar
frozenup-1.0.1.jar
ftb-backups-2.1.2.2.jar
ftb-chunks-forge-1605.3.2-build.115.jar
ftb-library-forge-1605.3.4-build.90.jar
ftb-quests-forge-1605.3.6-build.98.jar
ftb-ranks-forge-1605.1.6-build.33.jar
ftb-teams-forge-1605.2.3-build.40.jar
ImmersiveEngineering-1.16.5-5.1.0-148.jar
ImmersiveIndustry-1.16.5-0.1.8f.jar
ImmersivePetroleum-1.16.5-3.3.0-11.jar
ironchest-1.16.5-11.2.13.jar
item-filters-forge-1605.2.5-build.9.jar
jei-1.16.5-7.7.1.118.jar
Kiwi-1.16.5-3.6.1.jar
konkrete_1.3.0_MC_1.16.2-1.16.5.jar
kubejs-create-1605.1.4-build.12.jar
kubejs-forge-1605.3.18-build.152.jar
kubejs-immersive-engineering-1605.1.1-build.2.jar
lightfallclient-1.0.0.jar
mgui-1.16.5-3.3.0.jar
Morpheus-1.16.5-4.2.70.jar
MouseTweaks-2.14-mc1.16.2.jar
notenoughanimations-1.2.4.jar
PassableFoliage-1.16.5-2.4.0.jar
Patchouli-1.16.4-53.2.jar
ponderjs-1.16.5-1.0.3d.jar
primalwinter-forge-1.16.4-2.0.7.jar
rankine-1.16.5-1.3.2-hf5.jar
rhino-forge-1605.1.5-build.75.jar
selene-1.16.5-1.9.0.jar
shutupexperimentalsettings-1.0.3.jar
smoothboot-forge-1.16.4-1.2.2.jar
SnowRealMagic-1.16.4-2.7.2.jar
spark-forge.jar
steampowered-1.16.5-1.2.6.jar
stone-age-1.16.5-1.4.8.jar
stoneholm-1.2.2.jar
StorageDrawers-1.16.3-8.3.0.jar
StrongerSnowballs-1.16.5-5.0.1.jar
supplementaries-1.16.5-0.18.4.jar
tetra-1.16.5-3.20.0.jar
theoneprobe-1.16-3.1.4.jar
thermopolium-1.16.5-0.2.14.jar
Tips-1.16.5-4.0.7.jar
towers_of_the_wild-1.16.3-2.1.0.1.jar
TRansliterationLib-1.0.4.jar
WaterSource-1.1.40-release-1.16.5.jar
worldshape-1.0.jar
YungsApi-1.16.4-Forge-13.jar

Here is the crash report:
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.client.main.Main.main(Main.java:149) ~[The-Winter-Rescue.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[18:02:50] [Render thread/FATAL]: Mixin apply failed controllable.mixins.json:client.IngameGuiMixin -> net.minecraft.client.gui.IngameGui: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/client/gui/IngameGui::afterPushMatrix with priority 1000 cannot inject into net/minecraft/client/gui/IngameGui::func_238453_b_(Lcom/mojang/blaze3d/matrix/MatrixStack;)V merged by com.teammoeg.frostedheart.mixin.client.IngameGuiMixin with priority 1000 [PREINJECT Applicator Phase -> controllable.mixins.json:client.IngameGuiMixin -> Prepare Injections ->  -> handler$zjc000$afterPushMatrix(Lcom/mojang/blaze3d/matrix/MatrixStack;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/client/gui/IngameGui::afterPushMatrix with priority 1000 cannot inject into net/minecraft/client/gui/IngameGui::func_238453_b_(Lcom/mojang/blaze3d/matrix/MatrixStack;)V merged by com.teammoeg.frostedheart.mixin.client.IngameGuiMixin with priority 1000 [PREINJECT Applicator Phase -> controllable.mixins.json:client.IngameGuiMixin -> Prepare Injections ->  -> handler$zjc000$afterPushMatrix(Lcom/mojang/blaze3d/matrix/MatrixStack;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.client.main.Main.main(Main.java:157) ~[The-Winter-Rescue.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:         at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: Caused by: java.lang.reflect.InvocationTargetException
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:         at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:         at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[18:02:50] [Render thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:         ... 4 more
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]:         at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]:         at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]:         at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]:         at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]:         at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]:         at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]:         at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]:         at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]:         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]:         at net.minecraft.client.main.Main.main(Main.java:157)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:648]:         ... 10 more
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:671]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [controllable.mixins.json:client.IngameGuiMixin] from phase [DEFAULT] in config [controllable.mixins.json] FAILED during APPLY
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:671]:         at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:671]:         at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:671]:         at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printStackTrace:671]:         ... 21 more
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/client/gui/IngameGui::afterPushMatrix with priority 1000 cannot inject into net/minecraft/client/gui/IngameGui::func_238453_b_(Lcom/mojang/blaze3d/matrix/MatrixStack;)V merged by com.teammoeg.frostedheart.mixin.client.IngameGuiMixin with priority 1000 [PREINJECT Applicator Phase -> controllable.mixins.json:client.IngameGuiMixin -> Prepare Injections ->  -> handler$zjc000$afterPushMatrix(Lcom/mojang/blaze3d/matrix/MatrixStack;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]:         at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]:         at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]:         at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]:         at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]:         at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]:         at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]:         at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]:         at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]:         at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]:         at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[18:02:50] [Render thread/INFO]: [java.lang.Throwable:printEnclosedStackTrace:713]:         ... 21 more
Exception in thread "Render thread"

Please help me, thank you

**Comment by MegPredator** [comment]
The second mixin probably belongs to a mod called frosted heart in your list

**Comment by MrCrayfish** [comment]
Unfortunately, the Minecraft 1.16.5 version of Controllable is no longer supported and fixes will not be provided.
