### ISSUE TITLE
'SDL_GameControllerGetSensorDataWithTimestamp' "Exit Code -1"

### ISSUE THREAD

**Issue by coltennial** [MrCrayfish/Controllable#443]
When booting the game with Forge 1.20.1-0.6.16 it boots fine, once I add Controllable 1.20..1-0.20.3 it crashes on the loading screen and displays this error:

The game crashed whilst rendering overlay
Error: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Error looking up function 'SDL_GameControllerGetSensorDataWithTimestamp': The specified procedure could not be found.

Exit Code -1

**Comment by coltennial** [comment]
Just found the Crash Report (sorry new to this)

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2023-08-27 10:21:36
Description: Rendering overlay

java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Error looking up function 'SDL_GameControllerGetSensorDataWithTimestamp': The specified procedure could not be found.

	at net.minecraft.Util.m_137559_(Util.java:218) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91239_(Minecraft.java:664) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:419) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:148) ~[forge-1.20.1-47.1.44-universal.jar%23165!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeGameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.44.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.UnsatisfiedLinkError: Error looking up function 'SDL_GameControllerGetSensorDataWithTimestamp': The specified procedure could not be found.

	at com.sun.jna.Function.<init>(Function.java:252) ~[jna-5.12.1.jar%23131!/:5.12.1 (b0)] {}
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:604) ~[jna-5.12.1.jar%23131!/:5.12.1 (b0)] {}
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:580) ~[jna-5.12.1.jar%23131!/:5.12.1 (b0)] {}
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566) ~[jna-5.12.1.jar%23131!/:5.12.1 (b0)] {}
	at com.sun.jna.Native.register(Native.java:1904) ~[jna-5.12.1.jar%23131!/:5.12.1 (b0)] {}
	at io.github.libsdl4j.jna.SdlNativeLibraryLoader.registerNativeMethods(SdlNativeLibraryLoader.java:26) ~[libsdl4j-2.26.4-1.2.jar%23167!/:?] {re:classloading}
	at io.github.libsdl4j.api.gamecontroller.SdlGamecontroller.<clinit>(SdlGamecontroller.java:69) ~[libsdl4j-2.26.4-1.2.jar%23167!/:?] {re:classloading}
	at com.mrcrayfish.controllable.client.input.sdl2.SDL2ControllerManager.updateMappings(SDL2ControllerManager.java:108) ~[controllable-forge-1.20.1-0.20.3.jar%23158!/:1.20.1-0.20.3] {re:classloading}
	at com.mrcrayfish.controllable.client.input.ControllerManager.onClientFinishedLoading(ControllerManager.java:132) ~[controllable-forge-1.20.1-0.20.3.jar%23158!/:1.20.1-0.20.3] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.handler$zzi000$controllableOnFinishedLoading(Minecraft.java:3429) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:574) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.1.44-universal.jar%23165!/:?] {re:classloading}
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.Util.m_137559_(Util.java:218) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91239_(Minecraft.java:664) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:419) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:148) ~[forge-1.20.1-47.1.44-universal.jar%23165!/:?] {re:classloading}
-- Overlay render details --
Details:
	Overlay name: net.minecraftforge.client.loading.ForgeLoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeGameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.44.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources
Stacktrace:
	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2326) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:735) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.44.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 333258224 bytes (317 MiB) / 704643072 bytes (672 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 32
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5950X 16-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 3080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2208
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3713
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 48712.57
	Virtual memory used (MB): 11160.27
	Swap memory total (MB): 16000.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.20.1-forge-47.1.44
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.13, NVIDIA Corporation
	Window size: 3840x2160
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_us
	CPU: 32x AMD Ryzen 9 5950X 16-Core Processor 
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		framework-forge-1.20.1-0.6.16.jar                 |Framework                     |framework                     |0.6.16              |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		forge-1.20.1-47.1.44-universal.jar                |Forge                         |forge                         |47.1.44             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		controllable-forge-1.20.1-0.20.3.jar              |Controllable                  |controllable                  |0.20.3              |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
	Crash Report UUID: cf356a0a-f623-4a80-be47-1e717d46f5fe
	FML: 47.1
	Forge: net.minecraftforge:47.1.44

**Comment by cpoftea** [comment]
Same issue. Installed sdl2-2.24.1, SteamOS

**Comment by aitor** [comment]
Same Issue. Any idea on this @MrCrayfish?

**Comment by urayoru113** [comment]
I faced same problem but it was not related to this project
I just googled it and found an issue here.

Then i solved this error by downloading `sdl2.dll` and plancing the file into the `C:\Windows\System32` folder

You can download sdl2.dll here [https://github.com/libsdl-org/SDL/releases](https://github.com/libsdl-org/SDL/releases)

For windows users, choose `SDL2-2.28.5-win32-x64.zip` 

I hope this will be helpful to you

**Comment by paradust7** [comment]
This seems to be the same bug a year later. In Ubuntu 22.04 LTS, in both Prism and Curseforge trying to launch SkyFactory 5. My OS is completely up to date. If I find a workaround, I'll post it.

```
Caused by: java.lang.UnsatisfiedLinkError: Error looking up function 'SDL_GameControllerGetSensorDataWithTimestamp': /lib/x86_64-linux-gnu/libSDL2.so: undefined symbol: SDL_GameControllerGetSensorDataWithTimestamp
	at com.sun.jna.Function.<init>(Function.java:252) ~[jna-5.12.1.jar%23114!/:5.12.1 (b0)]
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:604) ~[jna-5.12.1.jar%23114!/:5.12.1 (b0)]
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:580) ~[jna-5.12.1.jar%23114!/:5.12.1 (b0)]
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566) ~[jna-5.12.1.jar%23114!/:5.12.1 (b0)]
	at com.sun.jna.Native.register(Native.java:1904) ~[jna-5.12.1.jar%23114!/:5.12.1 (b0)]
	at io.github.libsdl4j.jna.SdlNativeLibraryLoader.registerNativeMethods(SdlNativeLibraryLoader.java:26) ~[libsdl4j-2.26.4-1.2.jar%23841!/:?]
	at io.github.libsdl4j.api.gamecontroller.SdlGamecontroller.<clinit>(SdlGamecontroller.java:69) ~[libsdl4j-2.26.4-1.2.jar%23841!/:?]
	at com.mrcrayfish.controllable.client.input.sdl2.SDL2ControllerManager.updateMappings(SDL2ControllerManager.java:108) ~[controllable-forge-1.20.1-0.20.3.jar%23486!/:1.20.1-0.20.3]
	at com.mrcrayfish.controllable.client.input.ControllerManager.onClientFinishedLoading(ControllerManager.java:132) ~[controllable-forge-1.20.1-0.20.3.jar%23486!/:1.20.1-0.20.3]
```

EDIT: I was able to get it working by building and installing SDL 2.30.11 directly from https://github.com/libsdl-org/SDL/releases, and then changing the symlink `/lib/x86_64-linux-gnu/libSDL2.so` to use the newer version. It appears the SDL2 that is bundled with 22.04 LTS is just too old.

**Comment by MrCrayfish** [comment]
I am working on a new update for Controllable that will make the natives I provide in the JAR loaded first. The problem right now is that the JNA (library that loads and binds native functions) is first looking for installations on your system, and will only load from the JAR is nothing is found. The version you have on your system might not match up with the native functions I am expecting in Controllable, and hence an `UnsatisfiedLinkError` occurs.
