### ISSUE TITLE
crashing when opening brewing stand in relation to other mod

### ISSUE THREAD

**Issue by Knight-Hare** [MrCrayfish/Controllable#485]
The game crashes in relation to the better recipe book mod (brb-1.8.2-fabric.jar) when brewing stand is opened and the left joystick is pressed in any direction bringing up the cursor. There is no issue when the mods are on and the keyboard and mouse are used instead of a controller.

- Modloader:
Fabric 0.15.0

- Minecraft Version
1.20.1

- Mod Version
controllable-fabric-1.20.1-0.20.2.jar
brb-1.8.2-fabric.jar

- Relevant log output:
java.lang.NullPointerException: Cannot read field "field_22764" because "forwardButton" is null
	at com.mrcrayfish.controllable.client.overlay.RecipeBookOverlay.render(RecipeBookOverlay.java:62)
	at com.mrcrayfish.controllable.client.OverlayHandler.draw(OverlayHandler.java:42)
	at net.minecraft.class_757.handler$zfi000$controllable$controllableLastRender(class_757.java:2148)
	at net.minecraft.class_757.method_3192(class_757.java:975)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Knight-Hare** [comment]
Issue resolved by other mod creator

**Comment by MrCrayfish** [comment]
Thanks for the report. I've gone ahead and added a fix anyway. f1116dcc9af7123743d92fea011e6804f4c81495
