### ISSUE TITLE
Hitting the right D-Pad in any menu when in-game causes the game to crash? On steam deck btw.

### ISSUE THREAD

**Issue by Termulus** [MrCrayfish/Controllable#506]
Silly goofy crash report:

 ----
// On the bright side, I bought you a teddy bear!

Time: 2024-03-23 22:22:52
Description: Unexpected error

java.lang.NoClassDefFoundError: mezz/jei/gui/elements/GuiIconButton
	at com.mrcrayfish.controllable.platform.ForgeClientHelper.getJeiNavigationPoints(ForgeClientHelper.java:144) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.ControllerInput.gatherNavigationPoints(ControllerInput.java:1226) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.ControllerInput.navigateCursor(ControllerInput.java:1063) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.ControllerInput.handleButtonInput(ControllerInput.java:904) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.InputProcessor.processButton(InputProcessor.java:115) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.InputProcessor.processButtonStates(InputProcessor.java:80) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.InputProcessor.pollControllerInput(InputProcessor.java:54) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.InputProcessor.lambda$new$2(InputProcessor.java:45) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at com.mrcrayfish.framework.api.event.TickEvents.lambda$static$0(TickEvents.java:11) ~[framework-forge-1.20.1-0.6.27.jar%23259!/:1.20.1-0.6.27] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.framework.client.ClientForgeEvents.onRenderTick(ClientForgeEvents.java:50) ~[framework-forge-1.20.1-0.6.27.jar%23259!/:1.20.1-0.6.27] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.framework.client.__ClientForgeEvents_onRenderTick_ClientTickEvent.invoke(.dynamic) ~[framework-forge-1.20.1-0.6.27.jar%23259!/:1.20.1-0.6.27] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreClientTick(ForgeEventFactory.java:935) ~[forge-1.20.1-47.2.21-universal.jar%23315!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:aether.mixins.json:common.ForgeEventFactoryMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1745) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:APP:mixins.essential.json:client.Mixin_RunEssentialTasks,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.vanilla.Mixin_WorkaroundBrokenFramebufferBlitBlending,pl:mixin:APP:mixins.essential.json:feature.emote.Mixin_AllowMovementDuringEmoteWheel_HandleKeybinds,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:APP:mixins.essential.json:client.Mixin_RunEssentialTasks,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.vanilla.Mixin_WorkaroundBrokenFramebufferBlitBlending,pl:mixin:APP:mixins.essential.json:feature.emote.Mixin_AllowMovementDuringEmoteWheel_HandleKeybinds,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23310!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:APP:mixins.essential.json:client.Mixin_RunEssentialTasks,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.vanilla.Mixin_WorkaroundBrokenFramebufferBlitBlending,pl:mixin:APP:mixins.essential.json:feature.emote.Mixin_AllowMovementDuringEmoteWheel_HandleKeybinds,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.21.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.21.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.21.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}
Caused by: java.lang.ClassNotFoundException: mezz.jei.gui.elements.GuiIconButton
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Controllable (controllable), Version: 0.20.3
		Issue tracker URL: https://github.com/MrCrayfish/Controllable/issues
		at TRANSFORMER/controllable@0.20.3/com.mrcrayfish.controllable.platform.ForgeClientHelper.getJeiNavigationPoints(ForgeClientHelper.java:144)

	Framework (framework), Version: 0.6.27
		at TRANSFORMER/framework@0.6.27/com.mrcrayfish.framework.api.event.TickEvents.lambda$static$0(TickEvents.java:11)
Stacktrace:
	at com.mrcrayfish.controllable.platform.ForgeClientHelper.getJeiNavigationPoints(ForgeClientHelper.java:144) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.ControllerInput.gatherNavigationPoints(ControllerInput.java:1226) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.ControllerInput.navigateCursor(ControllerInput.java:1063) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.ControllerInput.handleButtonInput(ControllerInput.java:904) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.InputProcessor.processButton(InputProcessor.java:115) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.InputProcessor.processButtonStates(InputProcessor.java:80) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.InputProcessor.pollControllerInput(InputProcessor.java:54) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.controllable.client.InputProcessor.lambda$new$2(InputProcessor.java:45) ~[controllable-forge-1.20.1-0.20.3.jar%23245!/:1.20.1-0.20.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at com.mrcrayfish.framework.api.event.TickEvents.lambda$static$0(TickEvents.java:11) ~[framework-forge-1.20.1-0.6.27.jar%23259!/:1.20.1-0.6.27] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.framework.client.ClientForgeEvents.onRenderTick(ClientForgeEvents.java:50) ~[framework-forge-1.20.1-0.6.27.jar%23259!/:1.20.1-0.6.27] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mrcrayfish.framework.client.__ClientForgeEvents_onRenderTick_ClientTickEvent.invoke(.dynamic) ~[framework-forge-1.20.1-0.6.27.jar%23259!/:1.20.1-0.6.27] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreClientTick(ForgeEventFactory.java:935) ~[forge-1.20.1-47.2.21-universal.jar%23315!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:aether.mixins.json:common.ForgeEventFactoryMixin,pl:mixin:A}

**Comment by MrCrayfish** [comment]
Fixed in 0.21.0+ versions of Controllable
