### ISSUE TITLE
1.14.4-28.1.92 Server Crash Error Rerport

### ISSUE THREAD

**Issue by DvlDddy** [MrCrayfish/Controllable#51]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 11/27/19 3:39 PM
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:78) ~[?:28.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:234) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$buildMods$26(ModLoader.java:214) ~[?:?] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:216) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$18(ModLoader.java:173) ~[?:?] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:175) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221] {}
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:28.1] {re:classloading}
	... 24 more
Caused by: net.minecraftforge.fml.ModLoadingException: Controllable has class loading errors
§7net/minecraft/client/gui/toasts/IToast
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:77) ~[?:28.1] {re:classloading}
	at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:28.1] {re:classloading}
	... 24 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/toasts/IToast
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221] {}
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:28.1] {re:classloading}
	at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:28.1] {re:classloading}
	... 24 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.toasts.IToast
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_221] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:103) ~[modlauncher-4.1.0.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221] {}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221] {}
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:28.1] {re:classloading}
	at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:28.1] {re:classloading}
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2363695184 bytes (2254 MB) / 3449815040 bytes (3290 MB) up to 4772593664 bytes (4551 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms3G -Xmx5G
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.92.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.92.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.92.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.92.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.92.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.92
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: ~~ERROR~~ NullPointerException: null
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by DvlDddy** [comment]
I'm an idiot.
