### ISSUE TITLE
1.16.5 Crash

### ISSUE THREAD

**Issue by Toastable0** [MrCrayfish/Controllable#519]
When i try to launch MultiMC with ONLY version 0.13.3 for 1.16.5, it crashes.
Edit: It does work when i open without the mod

MultiMC version: 0.7.0-3857

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [2620:1ec:bdf::57, 13.107.246.57]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::57, 13.107.246.57]

api.mojang.com resolves to:
    [2620:1ec:bdf::57, 13.107.246.57]

Minecraft folder is:
C:/MultiMC/MultiMC/instances/1.16.5/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 22.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/MultiMC/MultiMC/instances/1.16.5/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/MultiMC/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/MultiMC/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/MultiMC/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/MultiMC/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/MultiMC/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/MultiMC/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/MultiMC/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/MultiMC/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/MultiMC/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/MultiMC/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/MultiMC/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/MultiMC/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/MultiMC/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/MultiMC/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/MultiMC/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/MultiMC/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/MultiMC/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/MultiMC/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/MultiMC/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/MultiMC/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/MultiMC/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/MultiMC/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/MultiMC/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/MultiMC/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/MultiMC/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc5/ForgeWrapper-mmc5.jar
  C:/MultiMC/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.2.34/forge-1.16.5-36.2.34-launcher.jar
  C:/MultiMC/MultiMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/MultiMC/MultiMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/MultiMC/MultiMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/MultiMC/MultiMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/MultiMC/MultiMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/MultiMC/MultiMC/libraries/cpw/mods/modlauncher/8.1.3/modlauncher-8.1.3.jar
  C:/MultiMC/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/MultiMC/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/MultiMC/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/MultiMC/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/MultiMC/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/MultiMC/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/MultiMC/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/MultiMC/MultiMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/MultiMC/MultiMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/MultiMC/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/MultiMC/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/MultiMC/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/MultiMC/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/MultiMC/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  C:/MultiMC/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/MultiMC/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/MultiMC/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] controllable-0.13.3-1.16.3.jar

Params:
  --username Able0 --version 1.16.5 --gameDir C:/MultiMC/MultiMC/instances/1.16.5/.minecraft --assetsDir C:/MultiMC/MultiMC/assets --assetIndex 1.16 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.34 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 18140

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2024-05-26 18:37:14,361 main WARN Advanced terminal features are not available in this environment
[18:37:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Able0, --version, 1.16.5, --gameDir, C:/MultiMC/MultiMC/instances/1.16.5/.minecraft, --assetsDir, C:/MultiMC/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.34, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[18:37:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 22.0.1 by Oracle Corporation
[18:37:14] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[18:37:14] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/MultiMC/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[18:37:15] [Thread-1/INFO] [STDERR/]: [org.lwjgl.system.ThreadLocalUtil:<clinit>:135]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[18:37:16] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.5, --gameDir, C:\MultiMC\MultiMC\instances\1.16.5\.minecraft, --assetsDir, C:\MultiMC\MultiMC\assets, --uuid, <PROFILE ID>, --username, Able0, --assetIndex, 1.16, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480]
[18:37:16] [main/WARN] [mixin/]: Error loading class: mezz/jei/input/MouseUtil (java.lang.ClassNotFoundException: null)
[18:37:16] [main/WARN] [mixin/]: Error loading class: mezz/jei/gui/overlay/IngredientListOverlay (java.lang.ClassNotFoundException: null)
[18:37:16] [main/WARN] [mixin/]: Error loading class: mezz/jei/gui/overlay/IngredientGridWithNavigation (java.lang.ClassNotFoundException: null)
[18:37:16] [main/WARN] [mixin/]: Error loading class: mezz/jei/gui/overlay/IngredientGrid (java.lang.ClassNotFoundException: null)
[18:37:16] [main/WARN] [mixin/]: Error loading class: mezz/jei/gui/PageNavigation (java.lang.ClassNotFoundException: null)
[18:37:20] [Render thread/WARN] [mixin/]: Error loading class: java/lang/Boolean (java.lang.IllegalArgumentException: Class file major version 66 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.Boolean)
[18:37:20] [Render thread/WARN] [mixin/]: Error loading class: java/lang/Boolean (java.lang.IllegalArgumentException: Class file major version 66 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.Boolean)
[18:37:20] [Render thread/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:246]: Failed to start Minecraft:
[18:37:20] [Render thread/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: java.lang.reflect.InvocationTargetException
[18:37:20] [Render thread/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[18:37:20] [Render thread/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:37:20] [Render thread/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
[18:37:20] [Render thread/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:37:20] [Render thread/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:37:20] [Render thread/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[18:37:20] [Render thread/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[18:37:20] [Render thread/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[18:37:20] [Render thread/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:682]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:682]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:682]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:682]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:682]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:682]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:682]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:682]: 	... 8 more
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:695]: Caused by: java.lang.reflect.InvocationTargetException
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:695]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:695]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:695]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:695]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:695]: 	... 13 more
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	at net.minecraft.client.main.Main.main(Main.java:157)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:718]: 	... 16 more
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:759]: Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: java.lang.Boolean
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:759]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:759]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:739)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:759]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:310)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:759]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:759]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:759]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:759]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:759]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:759]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[18:37:20] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:759]: 	... 28 more
[18:37:20] [Render thread/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[18:37:20] [Client Shutdown Thread/WARN] [mixin/]: Error loading class: java/lang/Boolean (java.lang.IllegalArgumentException: Class file major version 66 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.Boolean)
[18:37:20] [Client Shutdown Thread/ERROR] [minecraft/Main]: Caught previously unhandled exception :
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at net.minecraft.client.main.Main$2.run(Main.java:130) ~[?:?] {re:classloading}
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: java.lang.Boolean
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:739) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:310) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	... 11 more
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 26 May 2024 18:40:44 -0500

**Comment by MrCrayfish** [comment]
Unfortunately, the Minecraft 1.16.5 version of Controllable is no longer supported and fixes will not be provided.
