### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by leon230199089** [MrCrayfish/Controllable#522]
i wanted to download mods about prism launcher but this error wont let me start minecraft. please help me

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2024-06-06 19:24:56,907 main WARN Advanced terminal features are not available in this environment
[19:24:56] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, PLy7koll2011, --version, 1.20.1, --gameDir, C:/Users/Leon/AppData/Roaming/PrismLauncher/instances/1.20.1/.minecraft, --assetsDir, C:/Users/Leon/AppData/Roaming/PrismLauncher/assets, --assetIndex, 5, --uuid, &lt;PROFIL-ID&gt;, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.23, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, --width, 854, --height, 480]
[19:24:56] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.11 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
[19:24:57] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[19:24:57] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[19:24:57] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[19:24:57] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Leon/AppData/Roaming/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23150!/ Service=ModLauncher Env=CLIENT
[19:24:57] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce RTX 4070/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.33, NVIDIA Corporation
[19:24:57] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Leon\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\fmlcore\1.20.1-47.2.23\fmlcore-1.20.1-47.2.23.jar is missing mods.toml file
[19:24:57] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Leon\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.2.23\javafmllanguage-1.20.1-47.2.23.jar is missing mods.toml file
[19:24:57] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Leon\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.2.23\lowcodelanguage-1.20.1-47.2.23.jar is missing mods.toml file
[19:24:57] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Leon\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\mclanguage\1.20.1-47.2.23\mclanguage-1.20.1-47.2.23.jar is missing mods.toml file
[19:24:58] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 11 dependencies adding them to mods collection
[19:24:58] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'emotecraft', Requested by: 'emotetweaks', Expected range: '[2.2.7-b.build,)', Actual version: '[MISSING]'
[19:24:59] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[19:24:59] [main/ERROR] [mixin/]: Mixin config bbb.mixins.json does not specify "minVersion" property
[19:24:59] [main/ERROR] [mixin/]: Mixin config azurelib.mixins.json does not specify "minVersion" property
[19:24:59] [main/ERROR] [mixin/]: Mixin config azurelib.forge.mixins.json does not specify "minVersion" property
[19:24:59] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, C:\Users\Leon\AppData\Roaming\PrismLauncher\instances\1.20.1\.minecraft, --assetsDir, C:\Users\Leon\AppData\Roaming\PrismLauncher\assets, --uuid, &lt;PROFIL-ID&gt;, --username, PLy7koll2011, --assetIndex, 5, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480]
[19:24:59] [main/WARN] [mixin/]: Reference map 'rechiseledchipped.refmap.json' for rechiseled_chipped.mixins.json could not be read. If this is a development environment you can ignore this message
[19:24:59] [main/INFO] [Embeddium/]: Loaded configuration file for Embeddium: 44 options available, 0 override(s) found
[19:24:59] [main/INFO] [Embeddium-GraphicsAdapterProbe/]: Searching for graphics cards...
[19:24:59] [main/INFO] [Embeddium-GraphicsAdapterProbe/]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce RTX 4070, version=DriverVersion=31.0.15.4633]
[19:24:59] [main/WARN] [Embeddium-Workarounds/]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[19:24:59] [main/WARN] [Embeddium-Workarounds/]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[19:24:59] [main/WARN] [mixin/]: Reference map 'EmoteTweaks-forge-refmap.json' for EmoteTweaks.mixins.json could not be read. If this is a development environment you can ignore this message
[19:24:59] [main/WARN] [mixin/]: Reference map 'immersive_paintings-common-refmap.json' for immersive_paintings.mixin.json could not be read. If this is a development environment you can ignore this message
[19:24:59] [main/WARN] [mixin/]: Reference map 'smallships-forge-refmap.json' for smallships.mixins.json could not be read. If this is a development environment you can ignore this message
[19:24:59] [main/WARN] [mixin/]: Reference map 'cristellib-forge-refmap.json' for cristellib.mixins.json could not be read. If this is a development environment you can ignore this message
[19:25:00] [main/WARN] [mixin/]: Error loading class: io/github/kosmx/emotes/common/network/objects/NetData (java.lang.ClassNotFoundException: io.github.kosmx.emotes.common.network.objects.NetData)
[19:25:00] [main/WARN] [mixin/]: @Mixin target io.github.kosmx.emotes.common.network.objects.NetData was not found EmoteTweaks.mixins.json:NetDataAccessor
[19:25:00] [main/WARN] [mixin/]: Error loading class: io/github/kosmx/emotes/server/network/AbstractServerEmotePlay (java.lang.ClassNotFoundException: io.github.kosmx.emotes.server.network.AbstractServerEmotePlay)
[19:25:00] [main/WARN] [mixin/]: @Mixin target io.github.kosmx.emotes.server.network.AbstractServerEmotePlay was not found EmoteTweaks.mixins.json:ServerEmotePlayMixin
[19:25:00] [main/WARN] [mixin/]: Error loading class: io/github/kosmx/emotes/main/config/ClientConfigSerializer (java.lang.ClassNotFoundException: io.github.kosmx.emotes.main.config.ClientConfigSerializer)
[19:25:00] [main/WARN] [mixin/]: @Mixin target io.github.kosmx.emotes.main.config.ClientConfigSerializer was not found EmoteTweaks.mixins.json:ClientConfigSerializerMixin
[19:25:00] [main/WARN] [mixin/]: Error loading class: io/github/kosmx/emotes/main/network/ClientEmotePlay (java.lang.ClassNotFoundException: io.github.kosmx.emotes.main.network.ClientEmotePlay)
[19:25:00] [main/WARN] [mixin/]: @Mixin target io.github.kosmx.emotes.main.network.ClientEmotePlay was not found EmoteTweaks.mixins.json:ClientEmotePlayMixin
[19:25:00] [main/WARN] [mixin/]: Error loading class: io/github/kosmx/emotes/arch/executor/Defaults (java.lang.ClassNotFoundException: io.github.kosmx.emotes.arch.executor.Defaults)
[19:25:00] [main/WARN] [mixin/]: @Mixin target io.github.kosmx.emotes.arch.executor.Defaults was not found EmoteTweaks.mixins.json:DefaultsMixin
[19:25:00] [main/WARN] [mixin/]: Error loading class: io/github/kosmx/emotes/main/EmoteHolder (java.lang.ClassNotFoundException: io.github.kosmx.emotes.main.EmoteHolder)
[19:25:00] [main/WARN] [mixin/]: @Mixin target io.github.kosmx.emotes.main.EmoteHolder was not found EmoteTweaks.mixins.json:EmoteHolderMixin
[19:25:00] [main/WARN] [mixin/]: Error loading class: io/github/kosmx/emotes/main/screen/EmoteMenu (java.lang.ClassNotFoundException: io.github.kosmx.emotes.main.screen.EmoteMenu)
[19:25:00] [main/WARN] [mixin/]: @Mixin target io.github.kosmx.emotes.main.screen.EmoteMenu was not found EmoteTweaks.mixins.json:EmoteScreenMixin
[19:25:00] [main/WARN] [mixin/]: Error loading class: io/github/kosmx/emotes/arch/executor/types/Key (java.lang.ClassNotFoundException: io.github.kosmx.emotes.arch.executor.types.Key)
[19:25:00] [main/WARN] [mixin/]: @Mixin target io.github.kosmx.emotes.arch.executor.types.Key was not found EmoteTweaks.mixins.json:KeyMixin
[19:25:00] [main/ERROR] [Embeddium/]: Could not find embeddium mod, there is likely a dependency error. Skipping mixin application.
[19:25:00] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.6).
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.23/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.23/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.23/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 15 more
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: class net.minecraft.world.level.block.SkullBlock tried to access private field net.minecraft.world.level.block.state.StateDefinition$Builder.f_61096_ (net.minecraft.world.level.block.SkullBlock and net.minecraft.world.level.block.state.StateDefinition$Builder are in module minecraft@1.20.1 of loader 'TRANSFORMER' @11c713b7)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.23/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:32)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:151)
	... 23 more
Caused by: java.lang.IllegalAccessError: class net.minecraft.world.level.block.SkullBlock tried to access private field net.minecraft.world.level.block.state.StateDefinition$Builder.f_61096_ (net.minecraft.world.level.block.SkullBlock and net.minecraft.world.level.block.state.StateDefinition$Builder are in module minecraft@1.20.1 of loader 'TRANSFORMER' @11c713b7)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.SkullBlock.handler$zci000$amendments$addWaterlogging(SkullBlock.java:593)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.SkullBlock.m_7926_(SkullBlock.java:66)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Block.<init>(Block.java:171)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.BaseEntityBlock.<init>(BaseEntityBlock.java:15)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.AbstractSkullBlock.<init>(AbstractSkullBlock.java:21)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.SkullBlock.<init>(SkullBlock.java:31)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:491)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.FireBlock.m_53484_(FireBlock.java:301)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:46)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.lambda$main$0(Main.java:151)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Exiting with ERROR
Der Prozess wurde mit Status 2 beendet.

**Comment by MartyX98** [comment]
This literally has nothing to do with Controllable. From reading the logs, it seems like you're missing some dependency mods. I suggest closing this issue.
