### ISSUE TITLE
So Im trying to play Enigmatica 9 Expert and whenever I try to use the Dpad while in inventory I get this crashing error report.

### ISSUE THREAD

**Issue by Waffleking67** [MrCrayfish/Controllable#529]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-08-02 07:19:15
Description: Unexpected error

java.lang.ClassCastException: class dev.emi.emi.jemi.runtime.JemiIngredientListOverlay cannot be cast to class com.mrcrayfish.controllable.mixin.client.jei.IngredientListOverlayMixin (dev.emi.emi.jemi.runtime.JemiIngredientListOverlay is in module emi@1.1.6+1.19.2+forge of loader 'TRANSFORMER' @a5e8260; com.mrcrayfish.controllable.mixin.client.jei.IngredientListOverlayMixin is in module controllable@0.18.0 of loader 'TRANSFORMER' @a5e8260)
	at com.mrcrayfish.controllable.integration.ControllableJeiPlugin.lambda$getNavigationPoints$1(ControllableJeiPlugin.java:54) ~[controllable-0.18.0-1.19.2.jar%23425!/:0.18.0-1.19.2] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at com.mrcrayfish.controllable.integration.ControllableJeiPlugin.getNavigationPoints(ControllableJeiPlugin.java:49) ~[controllable-0.18.0-1.19.2.jar%23425!/:0.18.0-1.19.2] {re:classloading}
	at com.mrcrayfish.controllable.client.ControllerInput.gatherNavigationPoints(ControllerInput.java:1181) ~[controllable-0.18.0-1.19.2.jar%23425!/:0.18.0-1.19.2] {re:mixin,re:classloading}
	at com.mrcrayfish.controllable.client.ControllerInput.navigateMouse(ControllerInput.java:1033) ~[controllable-0.18.0-1.19.2.jar%23425!/:0.18.0-1.19.2] {re:mixin,re:classloading}
	at com.mrcrayfish.controllable.client.ControllerInput.handleButtonInput(ControllerInput.java:894) ~[controllable-0.18.0-1.19.2.jar%23425!/:0.18.0-1.19.2] {re:mixin,re:classloading}
	at com.mrcrayfish.controllable.Controllable.processButton(Controllable.java:307) ~[controllable-0.18.0-1.19.2.jar%23425!/:0.18.0-1.19.2] {re:mixin,re:classloading}
	at com.mrcrayfish.controllable.Controllable.processButtonStates(Controllable.java:262) ~[controllable-0.18.0-1.19.2.jar%23425!/:0.18.0-1.19.2] {re:mixin,re:classloading}
	at com.mrcrayfish.controllable.Controllable.controllerTick(Controllable.java:208) ~[controllable-0.18.0-1.19.2.jar%23425!/:0.18.0-1.19.2] {re:mixin,re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreClientTick(ForgeEventFactory.java:825) ~[forge-1.19.2-43.2.14-universal.jar%23616!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1718) ~[client-1.19.2-20220805.130853-srg.jar%23611!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078) ~[client-1.19.2-20220805.130853-srg.jar%23611!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23611!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23611!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23611!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.14.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	
	Full crash report:

[crash-2024-08-02_07.19.15-client.txt](https://github.com/user-attachments/files/16470378/crash-2024-08-02_07.19.15-client.txt)

**Comment by uthw** [comment]
I had this issue too. See if removing EMI fixes it, Controllable is incompatible with it

**Comment by Waffleking67** [comment]
It worked! Tysm!

**Comment by MrCrayfish** [comment]
Fixed in a1da7d52b25d07328cedc11f11d4286fa73a5333
