### ISSUE TITLE
crash with razer tartarus?

### ISSUE THREAD

**Issue by otakup0pe** [MrCrayfish/Controllable#93]
It's pretty consistent. This is on 1.12 single player creative mode. Happens whether I start the game fresh or if I plug in while the game is open. Even happens if I make sure the tartarus is properly configured and not showing up as a joystick and just mapping keys.

Let me know if there are other diagnostics I can provide. List of mods [here](https://github.com/tribesthatmaybe/modpack/blob/59ae7fa1cb9ca36c9e7d6fcc8c6ce5640a252cdf/packmaker.yml)

```
[18:17:06] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown!
java.lang.NoSuchMethodError: com.mrcrayfish.controllable.client.Controller.getState()Lcom/studiohartman/jamepad/ControllerStat
e;
        at com.mrcrayfish.guns.client.ControllerEvents.onRender(ControllerEvents.java:174) ~[ControllerEvents.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1354_ControllerEvents_onRender_RenderTickEvent.invoke(.d
ynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:
?]
        at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67) ~[Lag
Goggles-1.12.2-5.8-132.jar:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:355) ~[FMLCommonHandler.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) ~[bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
        at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
        at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
        at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
        at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by otakup0pe** [comment]
I think this is pretty much the issue mentioned [here](https://www.curseforge.com/minecraft/mc-mods/controllable?comment=289)

**Comment by MrCrayfish** [comment]
I won't be maintaining 1.12 anymore. I will allow PR if anyone wants to fix it.
